runtime: nodejs
env: flex
beta_settings:
  cloud_sql_instances: todo-flutter-8a80f:us-central1:buy-and-sell-db
env_variables:
  DB_USER: hapi-server
  DB_PASS: Password1
  DB_NAME: buy-and-sell
  DB_SOCKET: /cloudsql/todo-flutter-8a80f:us-central1:buy-and-sell-db